### ISSUE TITLE
Unknown flag "frame"

### ISSUE THREAD

**Issue by redaxmedia** [marionebl/svg-term-cli#16]
The frame flag is missing.

May I also suggest to refactor this great project using [commander.js](https://github.com/tj/commander.js/) as you reinvented the wheel.

It might also a good idea to have a `bin/svg-term` that includes just the commands and leave the project logic inside the src folder. You can find an example [here](https://github.com/redaxmedia/ncss-linter/blob/master/bin/ncss-linter).

## Setup

svg-term: 2.0.3
NodeJS: 8.7.0
NPM: 5.6.0
OS: Ubuntu 17.04

## Command

```
svg-term --cast 113643 --out examples/parrot.svg --frame --no-cursor --from=450
```

## Issue

> svg-term: remove unknown flags --frame

**Comment by marionebl** [comment]
This is a documentation issue.

I updated README.md to reflect the retirement of `--frame` in favor of `--window`.

**Comment by redaxmedia** [comment]
Okay, so close this issue then - I also made some off topic suggestions... but that is upon you of course.

**Comment by marionebl** [comment]
Re: commander. Sure I could do that, just have no inclination to invest the required time as long as the current implementation works well enough. 

If there crop up fundamental problems with it I'll revisit - thanks!
