### ISSUE TITLE
Comment colour not showing

### ISSUE THREAD

**Issue by lukechilds** [marionebl/svg-term-cli#17]
Hi, me again :)

In my shell (`zsh`) I have comments enabled. These show up light grey in my terminal, however `svg-term` outputs them as dark black. Seems like it's just falling back to the default SVG fill colourI because it can't detect it. Is there a way to fix this?

Currently manually adding `fill="#645240"` to the root SVG element to resolve the problem.

**Comment by lukechilds** [comment]
For example, this is my terminal:
https://i.imgur.com/DSeOCee.mp4

And this is what `svg-term` produces:

![](https://camo.githubusercontent.com/ad2029b099c793cd8cc570b1d1e7a2877eddb223/68747470733a2f2f7261776769742e636f6d2f6c756b656368696c64732f63686573742f6769662f64656d6f2f7465726d696e616c2e737667)

**Comment by marionebl** [comment]
Thanks for reporting, this should be fixed via https://github.com/marionebl/svg-term/commit/551c4ddc0ca77647574ef104973f663c7587ac20.

Make sure to have the latest `svg-term` transitive dep by:

```
npm remove -g svg-term-cli
npm install -g svg-term-cli
```

**Comment by marionebl** [comment]
The result I get for with all latest versions:

```
svg-term --cast RjJDZRRUESBCnPko2Qh1jd6CS --term hyper --window --out examples/chest.svg
```

![](https://cdn.rawgit.com/marionebl/svg-term-cli/master/examples/chest.svg)

**Comment by lukechilds** [comment]
Ah, I think GitHub's CDN had it an old version cached which led to some confusion. Thanks again!
