### ISSUE TITLE
Errors should be logged to `stderr` and not `stdout`

### ISSUE THREAD

**Issue by adius** [marionebl/svg-term-cli#20]
https://github.com/marionebl/svg-term-cli/blob/2b27a6d548a1d9673cc7fb865207235c2b8f586e/src/cli.ts#L492-L500

**Comment by adius** [comment]
And lines 496 and 497 should be reversed.

**Comment by marionebl** [comment]
* Logging to `stderr`: OK
* Reversing log order: No, I chose the order deliberately to have the actionable errors/warning right next to your prompt

**Comment by marionebl** [comment]
Different ways for of terminal usage for different peole I guess. Printing it **both** at the top and bottom might be worth exploring?

**Comment by adius** [comment]
If you're Ok with that, sounds good.
