### ISSUE TITLE
asciicast v2 compatibility

### ISSUE THREAD

**Issue by sickill** [marionebl/svg-term-cli#27]
Hey @marionebl ! Great job with this project 👍 

I'll be releasing asciinema 2.0 in the coming days, which uses new [asciicast v2 file format](https://github.com/asciinema/asciinema/blob/develop/doc/asciicast-v2.md), and was wondering if anything needs to be implemented to support it in svg-term-cli (I couldn't locate the actual code which reads the asciicast here). There are already many recordings on asciinema.org in v2 format made using `develop` branch of asciinema.

Let me know if you need any help!

**Comment by marionebl** [comment]
Hey @sickill, I'll investigate this weekend - can you post links to some v2 casts here? Thanks!

**Comment by marionebl** [comment]
For reference: The dependency chain for the code that reads the asciicast is:

`svg-term-cli` > [`svg-term`](https://github.com/marionebl/svg-term/blob/master/src/index.tsx#L78) > [`load-asciicast`](https://github.com/marionebl/load-asciicast)

load-asciicast in turn uses [asciinema-player/player/asciicast/load](https://github.com/asciinema/asciinema-player/blob/develop/src/asciinema/player/asciicast.cljs#L44).

**Comment by sickill** [comment]
I see, ok, then you should be covered is `load` supports v2 for a while now 👍 

Example v2 recording on asciinema.org:
https://asciinema.org/a/1RdOYnYtFebN6Xv7dv3thdBlt

And direct link to its asciicast file:
https://asciinema.org/a/1RdOYnYtFebN6Xv7dv3thdBlt.cast

**Comment by marionebl** [comment]
Works as expected:

![](https://cdn.rawgit.com/marionebl/ec17f8787afec69c59833524c880b591/raw/f7e0fd509ba9b1d32290e3d7cdb54b52594f62c8/v2.svg)

Thanks for reaching out 👍
