### ISSUE TITLE
Feature Request: Pause animation for couple of seconds

### ISSUE THREAD

**Issue by redaxmedia** [marionebl/svg-term-cli#28]
Hello,

I would like to pause short animations as the viewer cannot see what is going on in a short loop.

Command
-----------

Sleep/Pause in ms:

```
svg-term --cast xxx --out xxx.svg --pause 500
```

Example
----------

![Terminal Session](https://cdn.rawgit.com/redaxmedia/media/master/ncss-linter/terminal-session.svg)

**Comment by marionebl** [comment]
Thanks for the suggestion. I don't want to introduce features like this in `svg-term-cli`, editing/extended recording tools will not be part of its scope. 

I am rolling around the idea to provide something like a separate asciicast editor, which would include functionality like this.  

You might achieve the result you are after with some scripting (pseudo code):

```sh
#!/bin/sh
# screencast.sh
printf '\e[01;32mredaxmedia@redaxmedia\e[00m:\e[01;34m/mnt/WIP/ncss-linter\e[00m$ '
sleep 0.1
printf 'bin/ncss-linter --url=https://redaxmedia.com --namespace=rs --log-level=info'
bin/ncss-linter --url=https://redaxmedia.com --namespace=rs --log-level=info

sleep 500
echo ""
```

**Comment by redaxmedia** [comment]
I wonder why `--command` is not documented!?

Here comes a even more elegant way as I want to extend an the existing cast

```
svg-term --command="asciinema play https://asciinema.org/a/123683 && sleep 5 && echo" --out=123683.svg
```

**Comment by marionebl** [comment]
> I wonder why --command is not documented!?

Forgot to sync the docs with the cli, done via e22ca85.

**Comment by masaeedu** [comment]
@marionebl Is there instead some way to just stop the animation at the end instead of looping?
