### ISSUE TITLE
Extract a single frame

### ISSUE THREAD

**Issue by mathiasbynens** [marionebl/svg-term-cli#3]
Would it be feasible to extract just a single frame as an SVG?

**Comment by marionebl** [comment]
Sure, that is what [derhuerst/asciicast-to-svg](https://github.com/derhuerst/asciicast-to-svg) does. 
We'd have to implement this over at [marionebl/svg-term](https://github.com/marionebl/svg-term)-.

**Comment by marionebl** [comment]
Ping @mathiasbynens (Guess I completed my comment edits after you read it)

**Comment by marionebl** [comment]
Introduce via https://github.com/marionebl/svg-term-cli/commit/7ec55c4ec0b381bac237f0358eba48609544b674

**Comment by marionebl** [comment]
```sh
$ yarn global add svg-term-cli@latest
$ svg-term --version
1.1.0

svg-term --cast=3 --out nyancat.svg --frame --from=3000 --to=6000 #1
svg-term --cast=rfS1M5ynKm1hGaBqJYJj0mGCi --out jsvu.svg --frame -at 40000 # 2
```

**Comment by Timmmm** [comment]
Did the `--frame` option get removed? It would have been really useful...

**Comment by Timmmm** [comment]
Ah never mind, you don't need `--frame -at 10`, just `--at 10`.
