### ISSUE TITLE
asciicast v2 can't run #Fix

### ISSUE THREAD

**Issue by andy6804tw** [marionebl/svg-term-cli#32]
I'm use asciicast v2 from asciinema and download as `.cast` file but it can't run.

How to solve it? thx!

<img src="https://i.imgur.com/XkEkDga.png">

```
{ err: 'only asciicast v1 and v2 formats can be opened' }

/usr/local/lib/node_modules/svg-term-cli/lib/cli.js:406
            throw err;
            ^
only asciicast v1 and v2 formats can be opened
```

**Comment by andy6804tw** [comment]
@marionebl   
https://asciinema.org/a/L70phJLaN06JYUrJsIBbOLgEc

**Comment by marionebl** [comment]
Works for me with this command: `svg-term --cast L70phJLaN06JYUrJsIBbOLgEc`. Looking at your screenshot more closely I guess you mixed up the `--cast` and `--in` flags.
