### ISSUE TITLE
Optimizations or suggestions?

### ISSUE THREAD

**Issue by niftylettuce** [marionebl/svg-term-cli#35]
I currently use this for generating the console example at https://lass.js.org.

It however is pretty slow to render/load the page, despite the < 1 MB SVG file size.

Curious if you had any tips or flags to optimize it better.

**Comment by marionebl** [comment]
Thanks for reaching out! I haven‘t analysed your svg file in depth but two things that came to my mind 

* You might have better results when rendering/recording with a smaller width
* I remember yarn emitting more output than what can actually be seen with 30fps and asciinema faithfully recording that. The performance should improve when removing those frames from the asciinema file. Have a look at https://github.com/facebook/create-react-app/blob/master/tasks/screencast.js for an example
