### ISSUE TITLE
Animation not playing in MS PowerPoint

### ISSUE THREAD

**Issue by raidlman** [marionebl/svg-term-cli#57]
Not sure if this is a bug or just not supported in MS PowerPoint. Could be related to #11 

When inserting an svg created with svg-term, PowerPoint only show the first frame. Same in presentation mode. PP is also becoming realy slow and unresponsive.

Any ideas? The svg is playing fine in my browser.

**Comment by marionebl** [comment]
@raidlman I don't have the slightest idea what SVG renderer MS PowerPoint is using. I think there is not a lot we can do support it.

**Comment by marionebl** [comment]
I'll close this as I think there is little we can do on our end to support this.
