### ISSUE TITLE
term and profile seems not work.

### ISSUE THREAD

**Issue by liudonghua123** [marionebl/svg-term-cli#58]
I want to change the look and feel of the generated svg.
I executed the following command
```
svg-term --cast=udUD5QeJ5dBk0dF8fQsiyyppy --out quickstart1.svg --window
```
and 
```
svg-term --cast=udUD5QeJ5dBk0dF8fQsiyyppy --out quickstart2.svg --window --term iterm2 --profile  "Afterglow.itermcolors"
```
The `Afterglow.itermcolors` profile was download from https://github.com/mbadolato/iTerm2-Color-Schemes/tree/master/schemes, but the generated two files are the same.

I read the readme, but could not find how to use `term` and `profile` options.

**Comment by marionebl** [comment]
You'll want to install the `Afterglow` scheme in iTerm and then execute the command like this. Documentation could be clearer about this, also so #38 and #41.

```
svg-term --cast=udUD5QeJ5dBk0dF8fQsiyyppy --out quickstart2.svg --window --term iterm2 --profile  "Afterglow"
```

Produces the following cast according to my tests https://gist.github.com/marionebl/542f51bbce9d058a8243d27902b4c696

Let me know if this works for you.

**Comment by liudonghua123** [comment]
> You'll want to install the `Afterglow` scheme in iTerm and then execute the command like this. Documentation could be clearer about this, also so #38 and #41.
> 
> ```
> svg-term --cast=udUD5QeJ5dBk0dF8fQsiyyppy --out quickstart2.svg --window --term iterm2 --profile  "Afterglow"
> ```
> 
> Produces the following cast according to my tests https://gist.github.com/marionebl/542f51bbce9d058a8243d27902b4c696
> 
> Let me know if this works for you.

If I not use iTerm, like cmd in windows, then it will not work as expected?

**Comment by marionebl** [comment]
Ah, for this case you can actually use a local file as per 

```
svg-term --cast=udUD5QeJ5dBk0dF8fQsiyyppy --out quickstart2.svg --window --term iterm2 --profile  "./Afterglow.itermcolors"
```

Note the `./` needs to be in the file name

**Comment by liudonghua123** [comment]
@marionebl Hi, I tried your solution, but still got the same svg file.  Is there any relation with the windows cmd terminal. Or it does not support cmd.

**Comment by marionebl** [comment]
Sorry, can't test on windows as I don't have access to a installation of it.
