### ISSUE TITLE
Run the SVG through SVGO

### ISSUE THREAD

**Issue by sindresorhus** [marionebl/svg-term-cli#6]
To reduce the size. I can do this myself too, but would be better if it was built-in as most users would not think about doing this. I think it should be done here as it's too opinionated to do it in the programmatic API in `svg-term`.

**Comment by marionebl** [comment]
Yep, let's do this!

**Comment by sindresorhus** [comment]
One thing I noticed when I ran it through SVGO is that the "Collapse Useless Groups" feature needs to be disabled, as it removes any animated parts.

I used SVGO through https://jakearchibald.github.io/svgomg/ with https://github.com/sindresorhus/ora/blob/master/screenshot.svg

**Comment by marionebl** [comment]
Thanks for the hint, I recall to have stumbled over this and had no time to investigate - that helps a lot!
